### ISSUE TITLE
We need to update the README

### ISSUE THREAD

**Issue by bearecinos** [EdiGlacUQ/fenics_ice#100]
@dngoldberg @jrmaddison 

Waiting for a build I took the liberty of changing the readme ... txt is not nice as does not render in github.

.rst is much nicer: https://github.com/bearecinos/github_conda_workflow/blob/main/README.rst

You can add code blocks: https://github.com/bearecinos/github_conda_workflow/blob/main/README.rst#conda-installation

and [shields icons](https://shields.io/): https://github.com/bearecinos/github_conda_workflow/blob/main/README.rst#about

**Comment by dngoldberg** [comment]
LGTM!
