### ISSUE TITLE
1/2 factor missing when interp. velocity is subtracted from cloud velocity in `comp_J_inv()`

### ISSUE THREAD

**Issue by bearecinos** [EdiGlacUQ/fenics_ice#17]
In solver.py ->  `comp_J_inv()`

a 1/2 multiplication factor is missing probably along these lines [solver.py#L1194-L1197](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/solver.py#L1194-L1197):

```
u_mismatch = ((u_pts-u_obs_pts)/u_std_pts)
NormSqSolver(project(u_mismatch, obs_space), J_ls_term_u).solve()
v_mismatch = ((v_pts-v_obs_pts)/v_std_pts)
NormSqSolver(project(v_mismatch, obs_space), J_ls_term_v).solve()
```
following Eq.4 of the GMD paper 
![image](https://user-images.githubusercontent.com/16323300/144838645-9016dfda-e431-4a66-a71a-da4aa9b3900b.png)

@jrmaddison feel free to expand on this issue (or refer to) or open new ones regarding the changes that you plan to make to `comp_J_inv()`

**Comment by bearecinos** [comment]
Can this issue be close? @dngoldberg @jrmaddison

**Comment by bearecinos** [comment]
Yes I will update that toml value when I get a chance dont worry

**Comment by dngoldberg** [comment]
thank you!
