### ISSUE TITLE
Always import tlm_adjoint when importing fenics

### ISSUE THREAD

**Issue by jrmaddison** [EdiGlacUQ/fenics_ice#43]
```
from fenics import *
```

should always be followed by

```
from tlm_adjoint.fenics import *
```

Alternatively a 'backend' module could be added to fenics_ice containing these imports.

**Comment by bearecinos** [comment]
Hi @jrmaddison I actually tried this the other day ... I replaced all imports of fenics ``from fenics import *`` with ``from tlm_adjoint.fenics import *`` and most of the workflow failed ... I think we have an issue on how the code has been calling ufl, dolfin, fenics, and tml_adjoint ... this is very tricky .. I think we need to examine different python scripts one by one and decide when things are called from a specific library...

**Comment by jrmaddison** [comment]
This issue is that adding the extra tlm_adjoint imports changes when the annotation starts. We can prevent this by adding, in `__init__.py`,

```
from tlm_adjoint import stop_manager

stop_manager()
```

but we should then double check that this doesn't change annotation.

**Comment by jrmaddison** [comment]
Also we need both

```
from fenics import *
from tlm_adjoint.fenics import *
```

It's probably easiest to add these in a module, e.g. `backend.py` -- and this would let other modules avoid the `import *`s.
