### ISSUE TITLE
Allow setting of output frequency in timestep() and use inout.py for file format

### ISSUE THREAD

**Issue by dngoldberg** [EdiGlacUQ/fenics_ice#64]
In solver.timestep() the thickness and velocities are either saved every time step, or not at all. 
Additionally the inout module is not used at all, i don't think? Rather, fenics.XDMFFile package is used. We want to be able to control i/o though the inout module -- and XDMF formats are not amenable to visualisation with Python.  See below.

Propose a new functionality where frequency of output is specified, and `inout.write_variable()' is used instead. This will be rolled into a PR to address https://github.com/EdiGlacUQ/fenics_ice/issues/15. 

```
       if save_every_tstep:
            Hfile = Path(outdir) / "_".join((self.params.io.run_name,
                                             'H_ts.xdmf'))
            Ufile = Path(outdir) / "_".join((self.params.io.run_name,
                                             'U_ts.xdmf'))

            xdmf_hts = XDMFFile(self.mesh.mpi_comm(), str(Hfile))
            xdmf_uts = XDMFFile(self.mesh.mpi_comm(), str(Ufile))

            xdmf_hts.write(H_np, 0.0)
            xdmf_uts.write(U_np, 0.0)

**Comment by dngoldberg** [comment]
@bearecinos i am going to tackle this as a part of a new PR that implements melt rate. I would like to use your new `write_variable()` which allows for wither vtu or xml format. I am wondering which file format you have been using for your visualisation format, my aim is to allow visualisation without needing to use paraview. This the the motivation for not using XDMF, i can only figure out how to view XDMF with paraview.

**Comment by dngoldberg** [comment]
thanks @bearecinos . can you point me to an example in the fenics_ice code that writes a function to an h5 file?

**Comment by bearecinos** [comment]
[write_dqval()](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/inout.py#L223-L251) its a good example also I think you also want to put your function in the same inout.py section

**Comment by dngoldberg** [comment]
thanks @bearecinos! one more question, is there a reason you did not include h5 as an option in https://github.com/EdiGlacUQ/fenics_ice/pull/51 for output_var_format?

**Comment by bearecinos** [comment]
Because then I would have to write new functions to write the inversion output of each variable in that format too ... it was a bit of coding as I would have to modify a few functions to write variables in inout.py ... I was simply choosing not to write paraview as it's the format that makes the most clutter ... also to visualize inversion output the code reads in xml not h5... I could really write code to use both to be fare but I guess that is not a full priority atm?

**Comment by bearecinos** [comment]
maybe we should write an issue that unifies the format a bit more ... the choose of output format its very random in the whole code

**Comment by dngoldberg** [comment]
well, everything i come across tells me that xml will be deprecated, and you told me that you don't visualise with vtu -- so it seems natural to allow write_variable() to create h5 files as well as xml and vtu, no? I might be misunderstanding about new functions, i though write_variable() could be added to. Again, i might be misunderstanding is there a reason the below would not work?

```hdf5out = HDF5File(MPI.comm_world, str(outfname.with_suffix(".h5"), 'w')
        hdf5out.write(outvar, name)a
        hdf5out.close()

**Comment by dngoldberg** [comment]
i can test if you are not using bow for now?

**Comment by bearecinos** [comment]
yes, the above should work! the only thing is that I think there is a h5 file that actually saves the entire inversion output... I haven't look at it but its `_invout.h5` you might want to write to that instead of creating multiple files ... 
I am using bow but you can test this ... I am only using 16 cores though and jobs are really fast ..

**Comment by dngoldberg** [comment]
ok! yes i know h5 can save multiple time steps but there is not an easy "one size fits all" function for this, that i can think of.. so i thought it would be good to allow h5 for write_variable too.

sorry, will leave you alone now!

**Comment by bearecinos** [comment]
@dngoldberg I guess this was also solve by PR #68 ?
