### ISSUE TITLE
separate runscript for taylor tests outwith pytest

### ISSUE THREAD

**Issue by dngoldberg** [EdiGlacUQ/fenics_ice#67]
need a script in runs/ that will call taylor tests for inversion cost function (2nd order) and QoI cost function (1st order) for an experiment of choice. pytest taylor tests will be too limiting to look at complete functionality.

**Comment by dngoldberg** [comment]
hi @bearecinos we could conceivably work together on this, if you are able to start out as you say -- i can possibly add the capability to do the "QoI cost function (1st order)" once you get started?

**Comment by bearecinos** [comment]
yes that's what I was thinking ... will do the the script structure and should work like any other ones under runs/ ... will add this to my big PR
