### ISSUE TITLE
run_inv.py is writing out the wrong velocity observations 

### ISSUE THREAD

**Issue by bearecinos** [EdiGlacUQ/fenics_ice#74]
This needs to change as we use cloud_point observations and not the composite for the minimization of the cost function we should be writing:
```
# Observed velocities
        u_obs = self.u_obs
        v_obs = self.v_obs
        u_std = self.u_std
        v_std = self.v_std
        uv_obs_pts = self.uv_obs_pts

```

rather than `_obs_Q`'s these are set for initializing alpha only, at the moment we don't use it as we have alpha constant:

```
      inout.write_variable(mdl.u_obs_Q, params, outdir=diag_dir,
                             phase_name=phase_name, phase_suffix=phase_suffix)
      inout.write_variable(mdl.v_obs_Q, params, outdir=diag_dir,
                           phase_name=phase_name, phase_suffix=phase_suffix)
      inout.write_variable(mdl.u_std_Q, params, outdir=diag_dir,
                           phase_name=phase_name, phase_suffix=phase_suffix)
      inout.write_variable(mdl.v_std_Q, params, outdir=diag_dir,
                           phase_name=phase_name, phase_suffix=phase_suffix)

      U_obs = project((mdl.v_obs_Q**2 + mdl.u_obs_Q**2)**(1.0/2.0), mdl.M)
      U_obs.rename("uv_obs", "")
      inout.write_variable(U_obs, params, name="uv_obs", outdir=diag_dir,
                           phase_name=phase_name, phase_suffix=phase_suffix)
```

see [run_inv.py#L132-L144](https://github.com/EdiGlacUQ/fenics_ice/blob/main/runs/run_inv.py#L132-L144)

**Comment by bearecinos** [comment]
Hi @jrmaddison (or @dngoldberg) quick question: 

I tried to address this issue by writing the actual velocities that we do use in [solver.py/comp_J_inv(self, verbose=False)](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/solver.py#L1186-L1191) 

But I ran into trouble because the [inout.py/write_variable()](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/inout.py#L268-L275) function demands that such variables mdl.u_obs or self.u_obs should be a object type "Function", and not an array as they currently are in the vel_obs dictionary. 

I don't understand well the `comp_J_inv` part of the code and I will like to know where in there these observations are turn into a function so we can save them in the model object as the correct type "backend_Function = Function" or make them a function in run_inv.py before they are written... somewhere before this:  https://github.com/bearecinos/fenics_ice/blob/better_output/runs/run_inv.py#L132-L142 

This is not urgent but is not good that we are writing out the wrong input data use for the cost function. BTW the code is indeed using this cloud velocities (I already checked the output of the inversion cloud vs composite and the output of the model velocity is indeed very different)

**Comment by dngoldberg** [comment]
hi @bearecinos -- im not sure it makes sense to write out cloud point velocities as a function? as they are intended to be interpreted as a point, not gridded, velocities. there is no requirement, in comp_J_inv, on the spatial coverage of these points. There could be a single velocity value at a single location (which would lead to a very bad inversion, but it is still possible). You would not then write out a function associated with this point.

currently it is writing out mdl.u_obs_Q, mdl.v_obs_Q -- which are the mosaic velocities. this is still helpful as it enables visualisation. maybe one possibility, in model.py, is to generate similar functions using the cloud-point velocities, in the same way as is done with the mosaic velocities. It would be a less complete map, and we could think about how to best interpolate so we could see the gaps. what do you think of this as a solution?

Something else i did in the GMD paper was a histogram of point-wise errors. this is possible to do with point cloud data too.

you are off friday? maybe we can meet tomorrow to talk about these things with a whiteboard.

**Comment by bearecinos** [comment]
Hi Dan I see what you mean ... Yes I am thinking this might be a bit more complicated than I first thought then. I am good not writing them out also as I can always plot them from the original file (which is gridded and contains the nan.) but we can talk about this tomorrow, (I'll be in the office).
