### ISSUE TITLE
need for capability to sample from prior and posterior distributions

### ISSUE THREAD

**Issue by dngoldberg** [EdiGlacUQ/fenics_ice#78]
We need to be able to visualise random realisations of alpha and beta using the prior (and posterior) distributions. this requires implementing the functionality of [this module](https://github.com/EdiGlacUQ/fenics_ice/blob/GMD_branch/runs/run_sample_post.py)  in the main branch, and accounting for the dual inversion/ mixed function space. 

This will also require updates to prior.py which does not currently have a way to find the "square root" of the action and inverse action. Will also require the square root of the mass matrix, which is not implemented in the main branch.

I am developing a run module run_sample.py which will follow the preamble of the current run_errorprop.py. It is hoped this will be helpful in validating the greens function approach to understanding the physical significance of the prior, and also will give some degree of understanding of the posterior.

**Comment by dngoldberg** [comment]
@jrmaddison would you suggest copying https://github.com/EdiGlacUQ/sqrt_matrix/blob/main/sqrt_mass_matrix_action.py to the fenics_ice repo? or is there a better way to make use of it?

**Comment by jrmaddison** [comment]
Yes, adding to fenics_ice seems reasonable

**Comment by bearecinos** [comment]
Is this issue link to PR #82  if you make still changes to this PR could tag the issue by mentioned ... makes it easier to track what it has been done
