### ISSUE TITLE
potentially inconsistent use of prior implementation between inversion and eigendecomposition/error propagation

### ISSUE THREAD

**Issue by dngoldberg** [EdiGlacUQ/fenics_ice#79]
in prior.py, there are two classes, `Laplacian` and `Laplacian_flt` which inherits from Laplacian but overwrites the functional forms. 

in model.py, one or the other class is instantiated based on the presence of `delta_beta_gnd`:

https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/model.py#L546-L553

```python
    def get_prior(self):
        """Get the prior based on params"""
        if self.params.inversion.delta_beta_gnd is not None:
            logging.info("Using Laplacian prior with flotation")
            return prior.Laplacian_flt
        else:
            logging.info("Using Laplacian prior without flotation")
            return prior.Laplacian
```

In most run stages, `get_prior` is used, but in `run_eigendecompose()`, prior.laplacian is used explicitly

https://github.com/EdiGlacUQ/fenics_ice/blob/GMD_branch/runs/run_eigendec.py#L108

 `get_prior()` should be used here instead (and there may be other instances as well where get_prior() should be used)

**Comment by bearecinos** [comment]
@jrmaddison please correct me if I am wrong, but I think action() and inv_action() are defined in the [Laplacian class](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/prior.py#L277-L292) ... because the [Laplacian class](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/prior.py#L235-L292) is an inner class (or nested class) in [Laplacian_flt class](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/prior.py#L295), ``action()`` and ``inv_action()`` should be defined when we call ``prior.Laplacian_flt``:

```
 def get_prior(self):
        """Get the prior based on params"""
        if self.params.inversion.delta_beta_gnd is not None:
            logging.info("Using Laplacian prior with flotation")
            return prior.Laplacian_flt
        else:
            logging.info("Using Laplacian prior without flotation")
            return prior.
```

**Comment by jrmaddison** [comment]
`Laplacian_flt` inherits from `Laplacian`, which itself inherits from `Prior`, and the `Prior` constructor uses the `prior_form` method to set up the matrix and solver used by the `action` and `inv_action` methods. The `prior_form` method is overridden in `Laplacian_flt`.

**Comment by jrmaddison** [comment]
The relevant line in main is https://github.com/EdiGlacUQ/fenics_ice/blob/main/runs/run_eigendec.py#L139, and `reg_op`  has type as returned by `model.get_prior`.

**Comment by dngoldberg** [comment]
@jrmaddison -- sorry about this. i was looking in the GMD branch by mistake. i also had overlooked the inheritance issue. I think this means a code review needs to be more methodical.

**Comment by bearecinos** [comment]
agree ... perhaps something for this year [Hacktoberfest](https://www.digitalocean.com/blog/hacktoberfest-2021-recap)
