### ISSUE TITLE
Should we change conda for mamba? we need a setup.py file

### ISSUE THREAD

**Issue by bearecinos** [EdiGlacUQ/fenics_ice#96]
@jrmaddison, @dngoldberg 

Well conda as we had it before in the github actions is broken...

I dedicated my morning to try to build a Github actions workflow for fenics_ice using mamba. Works much better and is faster! I know that this can be a big change if you are not used to the tool but trust me its almost the same as conda, but works much better.

And we **can only do this for the github/actions as the workflow at the moment is broken.**

My wokflow test repository is here: https://github.com/bearecinos/github_conda_workflow

You can see under this link that the installation passes without problems
https://github.com/bearecinos/github_conda_workflow/runs/7249854742?check_suite_focus=true
 
I could be able to run the pytest there as well but there is an issue with both fenics_ice repository and tml_adjoint. 

the `conda develop` command is not available in mamba. So to install the repositories we need to use pip or python to install the package manually. To use that command we require both repositories fenics_ice and tml_adjoint to include a simple `setup.py` file.

If you wonder what is the difference between `setup.cfg` and `setup.py` there is a good blog info here: https://towardsdatascience.com/setuptools-python-571e7d5500f2

As I said in teams oggm has both! That makes the packages more user friendly giving users the possibility to install with pip. 

All we need to be in business is to have in both an extra `setup.py` that calls all the setup's specified in `setup.cfg`

```
#!/usr/bin/env python3
import setuptools
if __name__ == "__main__":
    setuptools.setup()
```

**Comment by dngoldberg** [comment]
hi @bearecinos i do not understand all of this text above. However i think you are saying that, for some reason, conda is no longer working? i noted this this morning when i tried to install miniconda and then fenics_ice on shin again. I got errors i did not understand when trying to create an environment from the yml file. Could this be related? this seems to be quite an issue but i don't completely understand it.

Anyhow -- i trust you with installation and will go with what you decide. if "mamba develop" does not exist, then it seems you want to allow fenics_ice to be installable via pip? and what does it mean to be installable by python -- does this simply mean adding paths to PYTHONPATH?

tbh i like being able to use embed(). i saw with oggm that when the code is installed via conda this does not work. will the same be true if installed via pip?

**Comment by bearecinos** [comment]
Hi @dngoldberg, 

I think it will be nice to be able to test an installation via pip, and test the embed() command, but we can't do that because to install the repo's of fenics_ice and tlm_adjoint via pip we need an extra file in Fenics_ice main folder repo and the tml_adjoint repo: 

a setup.py file containing the following text:
```
#!/usr/bin/env python3
import setuptools
if __name__ == "__main__":
    setuptools.setup()
```

This is because there isn't a mamba develop command. And the command `pip install -e .` requires the setup.py file.

I think it's best to discuss this with @jrmaddison next week I can probably try to explain the benefits of having these files and being able to install things with pip as well. I can keep working with my current conda environment...

> personal note: *I definitely dont want to encourage people to use mamba as I am not expert myself. I personally think is faster and for me things are the same, just that mamba is new and has a less functionalities but it will soon have most of the conda stuff*

If we want to update things, we will have to fix our environment, the github workflow will remain broken... and we will just have to wait for conda or dolfin to fix itself:

https://github.com/FEniCS/dolfinx/issues/2259

However, I think letting `install.sh` handle the installation via conda it's great (if the dependencies work), I just think that it would be nice to have an alternative when conda crashes ... Things *locally* (in our machines) do not have to change. The changes that I am proposing, just add extra functionalities and make the github/workflow more stable. 

Cheers
Bea

**Comment by dngoldberg** [comment]
hi bea

> This is because there isn't a mamba develop command. And the command pip install -e . requires the setup.py file.

yes i understood that there is not a `mamba develop` command. but i had forgotten about `pip install -e`. this is very easy to use. if the only thing missing (for fenics_ice) is an `install.py` i do not see the issue with adding it. I understand that James needs to agree on this for tlm_adjoint.

> Well conda as we had it before in the github actions is broken...

I don't think i actually understand why this is the case. Can you explain please?

**Comment by bearecinos** [comment]
>> if the only thing missing (for fenics_ice) is an install.py i do not see the issue with adding it. I understand that James needs to agree on this for tlm_adjoint.

I dont know if that will work with install.py I think it needs to be called setup.py 😅 

> I don't think i actually understand why this is the case. Can you explain please?

Ok (sorry if I am too specific I just want to be very clear)
Github actions installs the fenics_ice environment via conda in the runner machine (the virtual machine in github server that runs all commands under [test-fice.yml](https://github.com/EdiGlacUQ/fenics_ice/blob/main/.github/workflows/test-fice.yml#L22-L53)). If the fenics/dolfinx install fails or any other dependency fails or the conda package itself is broken... the github workflow is also broken. Every time you push a PR to the main branch `EdiGlacUQ/fenics_ice` you will start a CI workflow that fails ... hence the ❌ mark in the repo at the moment. 

On a side note:
@jrmaddison suggested using instead of an ubuntu virtual runner a debian based but that wont solve our problems in our local machines which are ubuntu based. I will test a debian runner machine as well in my github actions workflow repo just to see. But googling seems like the main issue is conda, and people are solving this by using mamba.

**Comment by dngoldberg** [comment]
ok thanks for this. 

>  If the fenics/dolfinx install fails or any other dependency fails or the conda package itself is broken...

do you know which of these is happening? as i said, i reinstalled miniconda on shin and now cannot create an environment from the fenics_ice yaml file. This could be due to the fenics install being broken, of course.

**Comment by bearecinos** [comment]
There is a discussion .. I can't understand if it is the fenics package or conda itself ... looks like its conda.

**Comment by dngoldberg** [comment]
can you direct me to the discussion? james mentioned something about this yesterday.

**Comment by bearecinos** [comment]
https://github.com/FEniCS/dolfinx/issues/2259#issuecomment-1177161754

**Comment by bearecinos** [comment]
Can you add an example below on how would you install it via pip in developing mode.

install the dev version + get access to the code.

e.g. I usually do that by:
```
git clone https://github.com/EdiGlacUQ/tlm_adjoint.git
cd tlm_adjoint
pip install -e .
```

`pip install -e .` requires the setup.py file mentioned above

**Comment by jrmaddison** [comment]
tlm_adjoint has a setup.py, https://github.com/jrmaddison/tlm_adjoint/blob/7ada4482f01f70b644778c17e6c302cba62deb3c/setup.py

**Comment by bearecinos** [comment]
cool then I just need to add one fore fenics_ice 😄
